import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F7FA',
    paddingHorizontal: 16,
  },
  chooseViewTitle: {
    marginTop: 12,
    marginLeft: 8,
  },
  chooseView: {
    width: '100%',
    height: 52,
    padding: 16,
    marginTop: 8,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 'bold',
    color: '#333333',
  },
  chooseText: {
    flex: 1,
    fontSize: 14,
    color: '#CCCCCC',
    lineHeight: 20,
  },
  titleRight: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 27,
    backgroundColor: '#F7F7FB',
    borderRadius: 12,
  },
  titleText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333333',
  },
  problemView: {
    width: '100%',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
  },
  toastTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 'bold',
    color: '#333333',
  },
  textArea: {
    width: '100%',
    minHeight: 80,
    marginTop: 8,
    fontSize: 14,
    color: '#333333',
    borderWidth: 0,
    textAlignVertical: 'top',
  },
  lengthToast: {
    fontSize: 12,
    lineHeight: 17,
    color: '#CCCCCC',
    textAlign: 'right',
    marginTop: 4,
  },
  imageList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  uploaderStyle: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 12,
  },
  imageItem: {
    width: 64,
    height: 64,
    borderRadius: 8,
    marginRight: 12,
    marginBottom: 12,
  },
  positionContainer: {
    position: 'relative',
  },
  deleteBtn: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 14,
    height: 14,
    zIndex: 10,
  },
  uploadText: {
    fontSize: 12,
    color: '#CCCCCC',
    marginTop: 4,
  },
  pageFooter: {
    width: '100%',
    alignItems: 'center',
  },
  footerBtn: {
    width: '100%',
    maxWidth: 196,
    height: 48,
    backgroundColor: '#333333',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnDisabled: {
    backgroundColor: '#999999',
  },
  footerBtnText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
