import { px, fontSize } from '@/utils/ui';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F7FA',
    paddingHorizontal: px(16),
  },
  chooseViewTitle: {
    marginTop: px(12),
    marginLeft: px(8),
  },
  chooseView: {
    width: '100%',
    height: px(52),
    padding: px(16),
    marginTop: px(8),
    marginBottom: px(12),
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedText: {
    flex: 1,
    fontSize: fontSize(14),
    lineHeight: px(20),
    fontWeight: 'bold',
    color: '#333333',
  },
  chooseText: {
    flex: 1,
    fontSize: fontSize(14),
    color: '#CCCCCC',
    lineHeight: px(20),
  },
  titleRight: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: px(10),
    height: px(27),
    backgroundColor: '#F7F7FB',
    borderRadius: px(12),
  },
  titleText: {
    fontSize: fontSize(12),
    fontWeight: 'bold',
    color: '#333333',
  },
  problemView: {
    width: '100%',
    padding: px(16),
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
  },
  toastTitle: {
    fontSize: fontSize(14),
    lineHeight: px(20),
    fontWeight: 'bold',
    color: '#333333',
  },
  textArea: {
    width: '100%',
    minHeight: px(80),
    marginTop: px(8),
    fontSize: fontSize(14),
    color: '#333333',
    borderWidth: 0,
    textAlignVertical: 'top',
  },
  lengthToast: {
    fontSize: fontSize(12),
    lineHeight: px(17),
    color: '#CCCCCC',
    textAlign: 'right',
    marginTop: px(4),
  },
  imageList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: px(12),
  },
  uploaderStyle: {
    width: px(64),
    height: px(64),
    borderRadius: px(8),
    backgroundColor: '#F2F2F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: px(12),
    marginBottom: px(12),
  },
  imageItem: {
    width: px(64),
    height: px(64),
    borderRadius: px(8),
    marginRight: px(12),
    marginBottom: px(12),
  },
  positionContainer: {
    position: 'relative',
  },
  deleteBtn: {
    position: 'absolute',
    top: px(-4),
    right: px(-4),
    width: px(14),
    height: px(14),
    zIndex: 10,
  },
  uploadText: {
    fontSize: fontSize(12),
    color: '#CCCCCC',
    marginTop: px(4),
  },
  pageFooter: {
    width: '100%',
    alignItems: 'center',
  },
  footerBtn: {
    width: '100%',
    maxWidth: px(196),
    height: px(48),
    backgroundColor: '#333333',
    borderRadius: px(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnDisabled: {
    backgroundColor: '#999999',
  },
  footerBtnText: {
    fontSize: fontSize(16),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
