import { fontSize, px } from '@/utils/ui';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: '#F3F4F7',
  },
  content: {
    paddingHorizontal: px(16),
    paddingTop: px(12),
    paddingBottom: px(20),
  },
  sectionTitle: {
    color: '#333333',
    fontSize: fontSize(14),
    fontWeight: '500',
    paddingLeft: px(8),
    marginBottom: px(8),
  },
  userName: {
    color: '#FF5A3A',
    fontWeight: '500',
  },
  uploadTitle: {
    color: '#333333',
    fontSize: fontSize(14),
    fontWeight: '500',
    paddingLeft: px(8),
    marginBottom: px(10),
  },
  cardBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
    paddingHorizontal: px(14),
    paddingVertical: px(10),
    marginBottom: px(12),
  },
  cardBox2: {
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
    paddingHorizontal: px(14),
    paddingBottom: px(6),
    paddingTop: px(2),
    marginBottom: px(12),
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: px(6),
  },
  radioItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioCircle: {
    width: px(18),
    height: px(18),
    borderRadius: px(9),
    borderWidth: 1,
    borderColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: px(8),
    backgroundColor: '#FFFFFF',
  },
  radioCircleActive: {
    borderColor: '#333333',
    backgroundColor: '#333333',
  },
  radioText: {
    color: 'rgba(33,33,33,0.8)',
    fontSize: fontSize(15),
  },
  innerDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.05)',
    marginVertical: px(4),
  },
  uploadBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: px(16),
  },
  uploadDivider: {
    width: px(1),
    height: px(48),
    backgroundColor: '#F1F1F1',
  },
  uploadItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  uploadLabel: {
    color: '#666666',
    fontSize: fontSize(14),
    marginBottom: px(10),
  },
  uploadPlaceholder: {
    width: px(64),
    height: px(64),
    borderRadius: px(8),
    backgroundColor: '#F9F9F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageWrap: {
    position: 'relative',
  },
  bankCardImage: {
    width: px(64),
    height: px(64),
    borderRadius: px(8),
  },
  imageClose: {
    position: 'absolute',
    right: px(-6),
    top: px(-6),
    width: px(16),
    height: px(16),
    borderRadius: px(8),
    backgroundColor: '#FF3D30',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageCloseText: {
    color: '#FFFFFF',
    fontSize: fontSize(10),
    lineHeight: px(10),
    fontWeight: '700',
  },
  formRow: {
    minHeight: px(48),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  formRowLast: {
    borderBottomWidth: 0,
  },
  formLabel: {
    color: '#333333',
    fontSize: fontSize(14),
    width: px(114),
    fontWeight: '500',
  },
  required: {
    color: '#FF4D4F',
  },
  formInput: {
    flex: 1,
    textAlign: 'left',
    color: '#333333',
    fontSize: fontSize(14),
    padding: 0,
  },
  formValue: {
    color: '#333333',
    fontSize: fontSize(14),
    maxWidth: '90%',
  },
  placeholderText: {
    color: '#CCCCCC',
  },
  codeWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  codeInput: {
    flex: 1,
    textAlign: 'left',
    color: '#333333',
    fontSize: fontSize(14),
    padding: 0,
    paddingRight: px(10),
  },
  codeBtn: {
    minWidth: px(98),
    height: px(34),
    borderRadius: px(17),
    backgroundColor: '#F1F2F6',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: px(12),
  },
  codeBtnDisabled: {
    opacity: 0.75,
  },
  codeBtnText: {
    color: '#333333',
    fontSize: fontSize(14),
    fontWeight: '500',
  },
  footerWrap: {
    backgroundColor: '#F3F4F7',
    paddingTop: px(8),
    paddingBottom: px(10),
    alignItems: 'center',
  },
  submitBtn: {
    width: px(196),
    height: px(48),
    borderRadius: px(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333333',
  },
  submitBtnDisabled: {
    backgroundColor: '#A9A9A9',
  },
  submitBtnText: {
    color: '#FFFFFF',
    fontSize: fontSize(16),
    fontWeight: '500',
  },
  popupWrap: {
    position: 'relative',
    paddingHorizontal: px(16),
    paddingBottom: px(14),
    minHeight: px(220),
  },
  popupListWrap: {
    position: 'relative',
  },
  searchWrap: {
    height: px(40),
    borderRadius: px(20),
    backgroundColor: '#F5F6F8',
    paddingHorizontal: px(12),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: px(14),
  },
  searchInput: {
    flex: 1,
    marginLeft: px(8),
    color: '#333333',
    fontSize: fontSize(14),
    paddingVertical: 0,
  },
  popupList: {
    maxHeight: px(340),
  },

  popupLoadingMask: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.88)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    elevation: 10,
  },
  popupLoading: {
    minHeight: px(160),
  },

  popupItem: {
    height: px(39),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: px(12),
  },
  bankIcon: {
    width: px(24),
    height: px(24),
  },
  bankName: {
    color: '#333333',
    fontSize: fontSize(14),
    fontWeight: '500',
  },
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: px(40),
    paddingBottom: px(40),
  },
  emptyText: {
    color: '#999999',
    fontSize: fontSize(14),
  },
  tempHint: {
    color: '#999999',
    fontSize: fontSize(13),
    marginBottom: px(10),
  },
  simpleOption: {
    minHeight: px(46),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F3F3',
    justifyContent: 'center',
  },
  simpleOptionText: {
    color: '#333333',
    fontSize: fontSize(15),
  },
  addressPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: px(18),
    position: 'absolute',
    top: px(-30),
    left: 0,
    width: '100%',
    zIndex: 10,
  },
  addressPickerCancelText: {
    color: '#7E8BA6',
    fontSize: fontSize(16),
  },
  addressPickerTitle: {
    color: '#333333',
    fontSize: fontSize(16),
    fontWeight: '600',
  },
  addressPickerConfirmText: {
    color: '#2F7BFF',
    fontSize: fontSize(16),
    fontWeight: '500',
    textAlign: 'right',
  },
  addressPickerBody: {
    backgroundColor: '#FFFFFF',
    paddingBottom: px(8),
  },
  addressPickerBodyWrap: {
    position: 'relative',
  },
  addressPickerIndicator: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#ECECEC',
  },
  addressPickerItemText: {
    color: '#333333',
    fontSize: fontSize(17),
  },
  radioIconWrap: {
    width: px(18),
    height: px(18),
    borderRadius: px(9),
    borderWidth: 1,
    borderColor: '#CCCCCC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: px(6),
  },
  radioIconWrapActive: {
    borderColor: 'rgba(33,33,33,0.8)',
    backgroundColor: 'rgba(33,33,33,0.8)',
  },
  statusWrap: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingTop: px(120),
    paddingHorizontal: px(24),
  },
  statusHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusIcon: {
    width: px(48),
    height: px(48),
    marginRight: px(10),
  },
  statusTitle: {
    color: '#333333',
    fontSize: fontSize(26),
    fontWeight: '500',
  },
  statusReasonText: {
    marginTop: px(22),
    color: '#999999',
    fontSize: fontSize(15),
    lineHeight: px(22),
  },
  statusActionBtn: {
    marginTop: px(120),
    width: px(210),
    height: px(48),
    borderRadius: px(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333333',
  },
  statusActionBtnText: {
    color: '#FFFFFF',
    fontSize: fontSize(16),
    fontWeight: '500',
  },
});
