import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F6F7FA',
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  titleLine: {
    width: 2,
    height: 12,
    marginRight: 4,
    backgroundColor: '#333333',
    borderRadius: 7,
  },
  titleText: {
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
  },
  swiperBox: {
    width: '100%',
    height: 170,
    marginTop: 12,
    borderRadius: 12,
    overflow: 'hidden',
  },
  swiperItem: {
    width: '100%',
    height: 170,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  dotWrap: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginHorizontal: 6,
  },
  toastText: {
    fontSize: 12,
    color: '#999999',
    marginTop: 8,
    marginBottom: 8,
  },
  imageList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
  },
  uploaderStyle: {
    backgroundColor: '#F2F2F2',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 12,
    paddingTop: 6,
    paddingHorizontal: 6,
    paddingBottom: 5,
  },
  imageItem: {
    width: 62,
    height: 62,
    borderRadius: 8,
  },
  positionContainer: {
    position: 'relative',
    marginRight: 12,
    marginBottom: 12,
  },
  deleteBtn: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 14,
    height: 14,
    zIndex: 5,
  },
  uploadText: {
    fontSize: 12,
    color: '#CCCCCC',
    lineHeight: 17,
  },
  problemView: {
    width: '100%',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginTop: 16,
  },
  textArea: {
    width: '100%',
    minHeight: 40,
    marginTop: 8,
    fontSize: 14,
    color: '#333333',
    padding: 0,
    textAlignVertical: 'top',
  },
  lengthToast: {
    fontSize: 12,
    color: '#CCCCCC',
    textAlign: 'right',
    marginTop: 4,
  },
  bannerTextBox: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 15,
  },
  adText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    textAlign: 'center',
  },
  videoPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageFooter: {
    width: '100%',
    // height: 80,
    alignItems: 'center',
    backgroundColor: 'transparent',
    // borderTopWidth: 1,
    // borderTopColor: 'rgba(0,0,0,0.06)',
  },
  footerBtn: {
    width: '100%',
    maxWidth: 196,
    height: 48,
    backgroundColor: '#333333',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
