import { StyleSheet } from 'react-native';
import { px, fontSize } from '@/utils/ui';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: '#F6F7FA',
  },
  content: {
    paddingHorizontal: px(16),
    paddingBottom: px(24),
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: px(12),
  },
  titleLine: {
    width: px(2),
    height: px(12),
    marginRight: px(4),
    backgroundColor: '#333333',
    borderRadius: px(7),
  },
  titleText: {
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
  },
  swiperBox: {
    width: '100%',
    height: px(170),
    marginTop: px(12),
    borderRadius: px(12),
    overflow: 'hidden',
  },
  swiperItem: {
    width: '100%',
    height: px(170),
    borderRadius: px(12),
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  dotWrap: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: px(8),
    marginBottom: px(8),
  },
  dot: {
    width: px(6),
    height: px(6),
    borderRadius: px(3),
    marginHorizontal: px(6),
  },
  toastText: {
    fontSize: fontSize(12),
    color: '#999999',
    marginTop: px(8),
    marginBottom: px(8),
  },
  imageList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: px(16),
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
  },
  uploaderStyle: {
    backgroundColor: '#F2F2F2',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: px(12),
    marginBottom: px(12),
    paddingTop: px(6),
    paddingHorizontal: px(6),
    paddingBottom: px(5),
  },
  imageItem: {
    width: px(68),
    height: px(68),
    borderRadius: px(8),
  },
  positionContainer: {
    position: 'relative',
    marginRight: px(12),
    marginBottom: px(12),
  },
  deleteBtn: {
    position: 'absolute',
    top: -px(4),
    right: -px(4),
    width: px(14),
    height: px(14),
    zIndex: px(5),
  },
  uploadText: {
    fontSize: fontSize(12),
    color: '#CCCCCC',
    lineHeight: px(17),
  },
  problemView: {
    width: '100%',
    padding: px(16),
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
    marginTop: px(16),
  },
  textArea: {
    width: '100%',
    minHeight: px(40),
    marginTop: px(8),
    fontSize: fontSize(14),
    color: '#333333',
    padding: px(0),
    textAlignVertical: 'top',
  },
  lengthToast: {
    fontSize: fontSize(12),
    color: '#CCCCCC',
    textAlign: 'right',
    marginTop: px(4),
  },
  bannerTextBox: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    padding: px(15),
  },
  adText: {
    fontSize: fontSize(16),
    fontWeight: 'bold',
    color: '#333333',
    textAlign: 'center',
  },
  videoPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageFooter: {
    width: '100%',
    // height: 80,
    alignItems: 'center',
    backgroundColor: 'transparent',
    // borderTopWidth: 1,
    // borderTopColor: 'rgba(0,0,0,0.06)',
  },
  footerBtn: {
    width: '100%',
    maxWidth: px(196),
    height: px(48),
    backgroundColor: '#333333',
    borderRadius: px(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnText: {
    fontSize: fontSize(16),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
});
