import { fontSize, px } from '@/utils/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: px(24),
    paddingTop: px(24),
  },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: px(8),
    position: 'relative',
    zIndex: 2,
  },
  sectionTitle: {
    fontSize: fontSize(14),
    fontWeight: '500',
    color: '#333333',
    lineHeight: px(20),
  },
  tips: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: px(4),
  },
  tipsText: {
    fontSize: fontSize(14),
    fontWeight: '500',
    color: '#333333',
    lineHeight: px(20),
  },
  noticeText: {
    position: 'absolute',
    right: 0,
    top: px(28),
    paddingHorizontal: px(12),
    paddingVertical: px(8),
    backgroundColor: '#333333',
    borderRadius: px(12),
    zIndex: 10,
    overflow: 'hidden',
    fontSize: fontSize(12),
    lineHeight: px(17),
    color: '#FFFFFF',
    maxWidth: px(260),
  },
  videoWrap: {
    position: 'relative',
    width: '100%',
    height: px(200),
    overflow: 'hidden',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: px(12),
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },
  video: {
    width: '100%',
    height: '100%',
  },
  poster: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  playOverlay: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playCircle: {
    width: px(48),
    height: px(48),
    borderRadius: px(24),
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyListWrap: {
    marginTop: px(15),
    padding: px(16),
    backgroundColor: '#F7F7FB',
    borderRadius: px(12),
    maxHeight: px(240),
  },
  keyListScroll: {
    width: '100%',
  },
  keyItem: {
    width: '100%',
    minHeight: px(32),
    marginBottom: px(12),
  },
  left: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: px(9),
    flex: 1,
    minWidth: 0,
  },
  keyItemText: {
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(20),
  },
  status: {
    fontSize: fontSize(9),
    color: '#FFFFFF',
    paddingHorizontal: px(5),
    paddingVertical: px(2),
    borderRadius: px(10),
    overflow: 'hidden',
  },
  statusCompleted: {
    backgroundColor: '#FD8E62',
  },
  statusUncompleted: {
    backgroundColor: '#999999',
  },
  right: {
    marginLeft: px(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioImg: {
    width: px(20),
    height: px(20),
  },
  footerWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: px(12),
    paddingHorizontal: px(24),
    backgroundColor: '#FFFFFF',
  },
  unbindBtn: {
    width: px(196),
    height: px(48),
    backgroundColor: '#333333',
    borderRadius: px(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  unbindBtnDisabled: {
    backgroundColor: '#999999',
  },
  unbindBtnText: {
    fontSize: fontSize(16),
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
