import { fontSize, px } from '@/utils/ui';
import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  contentBox: {
    flex: 1,
  },

  lockNameText: {
    marginTop: px(12),
    fontSize: fontSize(16),
    color: '#333333',
  },
  manualRow: {
    width: '100%',
    paddingHorizontal: px(28),
    marginVertical: px(20),
  },
  manualBtn: {
    alignItems: 'center',
    position: 'relative',
  },
  warningIcon: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 1,
  },
  manualIconCircle: {
    width: px(60),
    height: px(60),
    borderRadius: px(30),
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: px(8),
  },
  manualText: {
    fontSize: fontSize(12),
    color: '#333333',
  },
  cardsRow: {
    paddingHorizontal: px(16),
    gap: px(6),
  },
  card: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: px(12),
    padding: px(4),
    marginHorizontal: px(4),
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: px(4),
    elevation: 2,
  },
  mapCard: {
    marginRight: px(4),
  },
  cardHeader: {
    margin: px(12),
  },
  mapPreview: {
    width: '100%',
    height: px(80),
    borderRadius: px(8),
    overflow: 'hidden',
    marginBottom: px(8),
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  contentLeftBox: {
    width: px(165),
    backgroundColor: '#ffffff',
    borderRadius: px(12),
    paddingHorizontal: px(4),
    paddingTop: px(4),
    paddingBottom: px(8),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  singleHeight: {
    height: px(130),
  },
  multipleHeight: {
    height: px(172),
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  cardTitle: {
    flex: 1,
    marginLeft: px(8),
    fontSize: fontSize(14),
    color: '#333333',
  },
  cardSubTitle: {
    fontSize: fontSize(12),
    color: '#666666',
  },
  groupListBox: {
    marginTop: px(10),
    backgroundColor: '#F9F9F9',
    overflow: 'hidden',
    borderRadius: px(8),
    paddingVertical: px(23),
    paddingHorizontal: px(12),
    gap: px(20),
  },
  groupItem: {
    width: '100%',
  },
  groupItemImage: {
    width: px(20),
    height: px(20),
  },
  groupItemLockName: {
    fontWeight: '400',
    fontSize: fontSize(12),
    color: '#999999',
    marginLeft: px(8),
    maxWidth: px(100),
  },
  infoList: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    paddingHorizontal: px(12),
    paddingVertical: px(16),
    backgroundColor: '#F9F9F9',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: px(8),
    borderBottomRightRadius: px(8),
    gap: px(12),
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: px(4),
  },
  infoLabel: {
    fontSize: fontSize(12),
    color: '#999999',
    marginLeft: px(8),
    flex: 1,
  },
  infoValue: {
    fontSize: fontSize(12),
    color: '#333333',
  },
  entryList: {
    marginVertical: px(12),
    marginHorizontal: px(16),
    borderRadius: px(12),
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    padding: px(16),
    display: 'flex',
    flexDirection: 'column',
    gap: px(16),
  },
  entryItem: {
    flex: 1,
    paddingVertical: px(4),
  },
  entryText: {
    flex: 1,
    marginLeft: px(12),
    fontSize: fontSize(14),
    fontWeight: '400',
    color: '#333333',
  },
  manageBtn: {
    width: px(327),
    height: px(48),
    borderRadius: px(12),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },

  manageBtnText: {
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#FFFFFF',
  },

  manageDeteleBtn: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(0, 0, 0, 0.1)',
    borderWidth: 1,
    marginTop: px(12),
    color: '#666',
  },
  manageDeteleBtnText: {
    color: '#666',
  },
  toastTitle: {
    fontSize: fontSize(16),
    fontWeight: '500',
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'center',
    marginBottom: px(8),
  },
  toastContentText: {
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'center',
    width: '100%',
    marginBottom: px(8),
  },
  toastContentText1: {
    fontSize: fontSize(14),
    color: '#999999',
    lineHeight: px(20),
    textAlign: 'center',
    width: '100%',
  },
  dumpText: {
    marginTop: px(24),
    width: px(160),
    height: px(42),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333333',
    borderRadius: px(12),
  },
  dumpTextTitle: {
    fontWeight: '500',
    fontSize: fontSize(14),
    color: '#FFFFFF',
    lineHeight: px(20),
    textAlign: 'center',
    width: '100%',
  },
  toastSubTitleText: {
    fontSize: fontSize(14),
    color: '#999999',
    lineHeight: px(20),
    textAlign: 'center',
    width: '100%',
  },
  deviceImage: {
    width: '100%',
    aspectRatio: 526 / 296,
    marginTop: px(12),
  },
  openSwitchBtn: {
    marginTop: 'auto',
    width: px(124),
    height: px(42),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#333333',
    borderRadius: px(12),
  },
  openSwitchBtnText: {
    fontSize: fontSize(14),
    fontWeight: '500',
    color: '#FFFFFF',
    lineHeight: px(20),
    textAlign: 'center',
    width: '100%',
  },
  videoContent: {
    position: 'relative',
    width: '100%',
    height: px(160),
    borderRadius: px(12),
    overflow: 'hidden',
    marginTop: px(12),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  video: {
    width: '100%',
    height: '100%',
  },
  videoPoster: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  videoPlayBtn: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoPlayCircle: {
    width: px(120),
    height: px(120),
    borderRadius: px(60),
    alignItems: 'center',
    justifyContent: 'center',
  },
});
