import { px, fontSize } from '@/utils/ui';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    alignItems: 'center',
  },
  innerContent: {
    width: '100%',
  },
  cardImgWrapper: {
    position: 'relative',
    width: '100%',
    height: px(148),
  },
  cardImg: {
    width: '100%',
    height: px(148),
    borderRadius: px(12),
    overflow: 'hidden',
  },
  cardInfo: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    paddingRight: px(45),
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  emptyImage: {
    width: px(120),
  },
  stepImageContent: {
    width: px(280),
    height: px(75),
    marginTop: px(22),
    marginBottom: px(22),
  },
  stepImage: {
    width: '100%',
    height: '100%',
  },
  cardImage: {
    width: '100%',
    height: px(148),
    borderRadius: px(12),
    overflow: 'hidden',
  },
  cardInfoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    paddingRight: px(45),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  cardInfoText: {
    color: '#283E77',
    fontSize: fontSize(16),
    lineHeight: px(22),
    marginHorizontal: px(8),
    textAlign: 'center',
  },
  cardTimeText: {
    fontSize: fontSize(12),
    color: '#999999',
    textAlign: 'center',
    lineHeight: px(17),
  },
  infoBox: {
    width: '100%',
    backgroundColor: '#F8F7FC',
    borderRadius: px(12),
    paddingHorizontal: px(16),
    paddingTop: px(16),
    paddingBottom: px(8),
    marginTop: px(28),
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingBottom: px(12),
  },
  label: {
    fontSize: fontSize(14),
    lineHeight: px(20),
    fontWeight: 'bold',
    color: '#333333',
    width: px(80),
  },
  value: {
    flex: 1,
    fontSize: fontSize(14),
    lineHeight: px(20),
    color: '#333333',
    textAlign: 'right',
  },
  addressValue: {
    marginTop: px(4),
  },
  expressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: px(12),
  },
  expressNoText: {
    fontSize: fontSize(14),
    color: '#333333',
    marginRight: px(12),
    flex: 1,
  },
  copyIconWrap: {
    padding: px(4),
  },
  infoContent: {
    width: '100%',
    paddingHorizontal: px(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  fillItem: {
    width: '100%',
    height: px(48),
    borderRadius: px(12),
    backgroundColor: '#f7f7fb',
    marginBottom: px(8),
    paddingHorizontal: px(16),
  },
  fillLabel: {
    color: '#333333',
    fontSize: fontSize(14),
    lineHeight: px(20),
    fontWeight: 'bold',
  },
  fillInputContainer: {
    flex: 1,
  },
  fillInputText: {
    fontSize: fontSize(14),
    textAlign: 'right',
  },
  fillAddressText: {
    fontSize: fontSize(14),
    color: '#333333',
  },
  qrCodeContent: {
    width: '100%',
    marginTop: px(80),
    marginHorizontal: px(50),
    marginBottom: px(26),
    height: px(176),
    borderRadius: px(16),
    borderWidth: px(1),
    borderColor: '#EAEAEA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrCodeContent2: {
    width: '100%',
    marginTop: px(32),
    marginHorizontal: px(50),
    marginBottom: px(26),
    height: px(176),
    borderRadius: px(16),
    borderWidth: px(1),
    borderColor: '#EAEAEA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrCodeImage: {
    width: px(120),
    height: px(120),
    marginTop: px(8),
  },
  qrCodeContentText: {
    fontSize: fontSize(14),
    color: '#333333',
    marginTop: px(12),
    textAlign: 'center',
  },
  dividingLine: {
    height: px(1),
    width: px(60),
    backgroundColor: 'rgba(51,51,51,0.1)',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: fontSize(14),
    color: '#666666',
    marginTop: px(16),
    textAlign: 'center',
  },
  tipsBox: {
    marginTop: px(10),
  },
  tipsTitle: {
    fontSize: fontSize(12),
    color: '#CCCCCC',
    marginBottom: px(8),
  },
  tipsItem: {
    fontSize: fontSize(12),
    color: '#CCCCCC',
    lineHeight: px(17),
  },
  submitBtnText: {
    fontSize: fontSize(16),
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});

export default styles;
