import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  outContainer: {
    flex: 1,
    paddingLeft: 24,
    paddingRight: 24,
    flexDirection: 'column',
    alignItems: 'center',
  },
  innerTitle: {
    width: '100%',
    height: 22,
    fontWeight: '700',
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    textAlign: 'center',
  },
  mt200: {
    marginTop: 100,
  },
  innerToast: {
    width: '100%',
    height: 20,
    marginTop: 8,
    marginBottom: 16,
    fontWeight: '400',
    fontSize: 14,
    color: '#999999',
    lineHeight: 20,
    textAlign: 'center',
  },
  content: {
    marginTop: 16,
    backgroundColor: '#f7f7fb',
    borderRadius: 12,
    paddingLeft: 10,
    paddingRight: 10,
    width: 327,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
  },
  errorBorder: {
    borderWidth: 1,
    borderColor: '#ff2b24',
  },
  input: {
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    flex: 1,
    paddingVertical: 0,
  },
  smsCode: {
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    paddingLeft: 16,
    marginLeft: 16,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(0, 0, 0, 0.1)',
    minWidth: 112,
    textAlign: 'center',
  },
  noMobileSmsCode: {
    fontSize: 16,
    color: '#cccccc',
    lineHeight: 22,
    paddingLeft: 16,
    marginLeft: 16,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(0, 0, 0, 0.1)',
    minWidth: 112,
    textAlign: 'center',
  },
  codeToast: {
    width: '100%',
    height: 20,
    marginTop: 4,
    marginBottom: 12,
    fontWeight: '400',
    fontSize: 14,
    color: '#ff2b24',
    lineHeight: 20,
    textAlign: 'center',
  },
  btn: {
    width: 160,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendCodeBtn: {
    backgroundColor: '#333333',
  },
  verificationCodeBtn: {
    backgroundColor: '#999999',
  },
  btnText: {
    fontWeight: '700',
    fontSize: 16,
    color: '#ffffff',
    lineHeight: 22,
    textAlign: 'center',
  },
});

