import { StyleSheet } from 'react-native';
import { px, fontSize } from '@/utils/ui';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  outContainer: {
    flex: 1,
    paddingLeft: px(24),
    paddingRight: px(24),
    flexDirection: 'column',
    alignItems: 'center',
  },
  innerTitle: {
    width: '100%',
    height: px(22),
    fontWeight: '700',
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'center',
  },
  mt200: {
    marginTop: px(100),
  },
  innerToast: {
    width: '100%',
    height: px(20),
    marginTop: px(8),
    marginBottom: px(16),
    fontWeight: '400',
    fontSize: fontSize(14),
    color: '#999999',
    lineHeight: px(20),
    textAlign: 'center',
  },
  content: {
    marginTop: px(16),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
    paddingLeft: px(10),
    paddingRight: px(10),
    width: px(327),
    height: px(56),
    flexDirection: 'row',
    alignItems: 'center',
  },
  errorBorder: {
    borderWidth: px(1),
    borderColor: '#ff2b24',
  },
  input: {
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    flex: 1,
    paddingVertical: px(0),
  },
  smsCode: {
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    paddingLeft: px(16),
    marginLeft: px(16),
    borderLeftWidth: px(1),
    borderLeftColor: 'rgba(0, 0, 0, 0.1)',
    minWidth: px(112),
    textAlign: 'center',
  },
  noMobileSmsCode: {
    fontSize: fontSize(16),
    color: '#cccccc',
    lineHeight: px(22),
    paddingLeft: px(16),
    marginLeft: px(16),
    borderLeftWidth: px(1),
    borderLeftColor: 'rgba(0, 0, 0, 0.1)',
    minWidth: px(112),
    textAlign: 'center',
  },
  codeToast: {
    width: '100%',
    height: px(20),
    marginTop: px(4),
    marginBottom: px(12),
    fontWeight: '400',
    fontSize: fontSize(14),
    color: '#ff2b24',
    lineHeight: px(20),
    textAlign: 'center',
  },
  btn: {
    width: px(160),
    height: px(48),
    borderRadius: px(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendCodeBtn: {
    backgroundColor: '#333333',
  },
  verificationCodeBtn: {
    backgroundColor: '#999999',
  },
  btnText: {
    fontWeight: '700',
    fontSize: fontSize(16),
    color: '#ffffff',
    lineHeight: px(22),
    textAlign: 'center',
  },
});
