package com.boklock.m.test;

// Shim for dev applicationId so autogenerated entrypoint can reference BuildConfig.
public final class BuildConfig {
  public static final boolean IS_NEW_ARCHITECTURE_ENABLED =
      com.boklock.m.BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
  public static final boolean IS_EDGE_TO_EDGE_ENABLED =
      false;

  private BuildConfig() {}
}
