import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f6f7fa',
    paddingLeft: 16,
    paddingRight: 16,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    paddingBottom: 130,
  },
  pageFooter: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    height: 130,
    paddingBottom: 34,
    backgroundColor: '#ffffff',
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  editPageFooter: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    height: 98,
    paddingBottom: 34,
    backgroundColor: '#ffffff',
    borderRadius: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  footerBtn: {
    width: 196,
    height: 48,
    backgroundColor: '#333333',
    borderRadius: 16,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnText: {
    width: '100%',
    height: 22,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#ffffff',
    lineHeight: 22,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  vipRecord: {
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  mt24: { marginTop: 12 },
  mt32: { marginTop: 16 },
  mt40: { marginTop: 20 },
  infoBox: {
    backgroundColor: '#ffffff',
    width: '100%',
    borderRadius: 12,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 20,
    paddingBottom: 20,
  },
  deviceBox: {
    backgroundColor: '#ffffff',
    width: '100%',
    height: 'auto',
    borderRadius: 12,
  },
  itemContent: {
    width: '100%',
    height: 20,
  },
  label: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  input: {
    textAlign: 'right',
  },
  titleBox: {
    width: 327,
    height: 20,
  },
  titleLine: {
    width: 2,
    height: 12,
    backgroundColor: '#333333',
    borderRadius: 7,
    marginRight: 6,
  },
  titleText: {
    flex: 1,
    height: 20,
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  flex1: { flex: 1 },
  titleRight: {
    width: 72,
    height: 20,
    borderRadius: 0,
  },
  titleRightText: {
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#999999',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  timeBox: {
    width: 140,
    height: 69,
    borderRadius: 12,
    borderWidth: 0.5,
    borderStyle: 'solid',
    borderColor: '#ebebeb',
    paddingTop: 10,
    paddingLeft: 14,
    paddingBottom: 10,
    paddingRight: 14,
  },
  usageCount: {
    flex: 1,
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'right',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  chooseNum: {
    height: 17,
    fontWeight: 'normal',
    fontSize: 12,
    color: '#999999',
    lineHeight: 17,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  num: {
    width: '100%',
    height: 22,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  popTitleText: {
    height: 22,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  text: {
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  dateTimePopTitle: {
    width: '100%',
    paddingLeft: 16,
    paddingRight: 16,
    color: '#333333',
    fontSize: 14,
  },
  dateText: {
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  timeText: {
    height: 25,
    fontWeight: 'bold',
    fontSize: 18,
    color: '#333333',
    lineHeight: 25,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  useageCountTitle: {
    width: '100%',
  },
  chooseItem: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: 22,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  usageCountInput: {
    width: 327,
    height: 44,
    marginTop: 60,
    paddingRight: 12,
    borderRadius: 8,
    borderColor: 'rgba(0, 0, 0, 0.05)',
    borderWidth: 1,
    borderStyle: 'solid',
  },
  cancalBtn: {
    width: 156,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
    fontWeight: 'normal',
    fontSize: 16,
    color: '#999999',
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  confirmBtn: {
    width: 156,
    height: 48,
    marginLeft: 15,
    borderRadius: 12,
  },
  confirmBtnText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#ffffff',
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  bgColor999: { backgroundColor: '#999999' },
  bgColor333: { backgroundColor: '#333333' },
  userItem: {
    flex: 1,
    height: 46,
    backgroundColor: '#f7f7fb',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
  },
  activeUserItem: { borderColor: '#333333' },
  defaultUserItem: { borderColor: '#f7f7fb' },
  userItemText: {
    flex: 1,
    height: 22,
    fontWeight: 'normal',
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  mb24: { marginBottom: 12 },
  numPop: {
    width: '100%',
    height: 54,
    padding: 16,
    position: 'relative',
  },
  titleTextPop: {
    height: 22,
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  contentBox: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
    height: 339,
    marginLeft: 24,
    marginRight: 24,
    marginTop: 5,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: '#f7f7fb',
    borderRadius: 12,
  },
  pl48: { paddingLeft: 24 },
  pr32: { paddingRight: 16 },
  rowText1: {
    height: 20,
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  tagBox: {
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  color1: { color: '#ff873d' },
  color2: { color: '#37c22a' },
  color10: { color: '#999999' },
  color20: { color: '#e5140d' },
  inviteCode: {
    height: 50,
    fontWeight: 'bold',
    fontSize: 36,
    color: '#333333',
    lineHeight: 50,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  popTime: {
    width: 279,
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  timeBoxPop: {
    width: 307,
    height: 77,
    padding: 14,
    borderRadius: 12,
    borderWidth: 0.5,
    borderStyle: 'solid',
    borderColor: '#ebebeb',
  },
  mr12: { marginRight: 6 },
  mb8: { marginBottom: 4 },
  dateTextPop: {
    height: 20,
    fontWeight: 'normal',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  dateTime: {
    height: 25,
    fontWeight: 'normal',
    fontSize: 18,
    color: '#333333',
    lineHeight: 25,
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  popupCode: {
    paddingLeft: 24,
    paddingRight: 24,
  },
  cancalBtnPop: {
    width: 156,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
    fontWeight: 'normal',
    fontSize: 16,
    color: '#999999',
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  confirmBtnPop: {
    width: 156,
    height: 48,
    marginLeft: 15,
    borderRadius: 12,
    fontWeight: 'bold',
    lineHeight: 48,
    fontSize: 16,
    color: '#ffffff',
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  shareBtn: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    margin: 0,
    color: '#ffffff',
  },
  messageBadge: {
    position: 'absolute',
    bottom: 12,
    right: -8,
    height: 18,
    paddingLeft: 6,
    paddingRight: 6,
    paddingTop: 1,
    paddingBottom: 1,
    backgroundColor: '#ff2b24',
    borderRadius: 96,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageBadgeText: {
    height: 17,
    fontSize: 12,
    color: '#ffffff',
    lineHeight: 17,
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
});
