import { fontSize, px } from '@/utils/ui';
import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f6f7fa',
    paddingLeft: px(16),
    paddingRight: px(16),
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  pageFooter: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    height: px(120),
    paddingBottom: px(34),
    backgroundColor: '#ffffff',
    borderRadius: 0,
    borderTopWidth: px(1),
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  editPageFooter: {
    width: '100%',
    // position: 'absolute',
    // bottom: 0,
    height: px(98),
    paddingBottom: px(34),
    backgroundColor: '#ffffff',
    borderRadius: 0,
    borderWidth: px(1),
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  footerBtn: {
    width: px(196),
    height: px(48),
    backgroundColor: '#333333',
    borderRadius: px(16),
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerBtnText: {
    width: '100%',
    height: px(22),
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#ffffff',
    lineHeight: px(22),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  vipRecord: {
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  mt24: { marginTop: px(12) },
  mt32: { marginTop: px(16) },
  mt40: { marginTop: px(20) },
  infoBox: {
    backgroundColor: '#ffffff',
    width: '100%',
    borderRadius: px(12),
    paddingLeft: px(16),
    paddingRight: px(16),
    paddingTop: px(20),
    paddingBottom: px(20),
  },
  deviceBox: {
    backgroundColor: '#ffffff',
    width: '100%',
    height: 'auto',
    borderRadius: px(12),
  },
  itemContent: {
    width: '100%',
    height: px(20),
  },
  label: {
    fontWeight: 'bold',
    fontSize: fontSize(14),
    color: '#333333',
  },
  contentLabel: {
    width: px(120),
  },
  input: {
    textAlign: 'right',
    minWidth: px(120),
  },
  titleBox: {
    width: '100%',
    height: px(20),
  },
  titleLine: {
    width: px(2),
    height: px(12),
    backgroundColor: '#333333',
    borderRadius: px(7),
    marginRight: px(6),
  },
  titleText: {
    flex: 1,
    height: px(20),
    fontWeight: 'bold',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  flex1: { flex: 1 },
  titleRight: {
    width: px(72),
    height: px(20),
    borderRadius: 0,
    marginLeft: 'auto',
  },
  titleRightText: {
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#999999',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  timeBox: {
    width: px(140),
    height: px(69),
    borderRadius: px(12),
    borderWidth: px(0.5),
    borderStyle: 'solid',
    borderColor: '#ebebeb',
    paddingTop: px(10),
    paddingLeft: px(14),
    paddingBottom: px(10),
    paddingRight: px(14),
  },
  usageCount: {
    flex: 1,
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'right',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  chooseNum: {
    height: px(17),
    fontWeight: 'normal',
    fontSize: fontSize(12),
    color: '#999999',
    lineHeight: px(17),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  num: {
    width: '100%',
    height: px(22),
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  popTitleText: {
    height: px(22),
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  text: {
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  dateTimePopTitle: {
    width: '100%',
    paddingLeft: px(16),
    paddingRight: px(16),
    color: '#333333',
    fontSize: fontSize(14),
  },
  dateText: {
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  timeText: {
    height: px(25),
    fontWeight: 'bold',
    fontSize: fontSize(18),
    color: '#333333',
    lineHeight: px(25),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  useageCountTitle: {
    width: '100%',
  },
  chooseItem: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: px(22),
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  usageCountInput: {
    width: px(327),
    height: px(44),
    marginTop: px(60),
    paddingRight: px(12),
    borderRadius: px(8),
    borderColor: 'rgba(0, 0, 0, 0.05)',
    borderWidth: px(1),
    borderStyle: 'solid',
  },
  cancalBtn: {
    width: px(156),
    height: px(48),
    borderRadius: px(12),
    borderWidth: px(1),
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
    fontWeight: 'normal',
    fontSize: fontSize(16),
    color: '#999999',
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  confirmBtn: {
    width: px(156),
    height: px(48),
    marginLeft: px(15),
    borderRadius: px(12),
  },
  confirmBtnText: {
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#ffffff',
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  bgColor999: { backgroundColor: '#999999' },
  bgColor333: { backgroundColor: '#333333' },
  userItem: {
    flex: 1,
    height: px(46),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
    borderWidth: px(1),
    borderStyle: 'solid',
    paddingTop: px(12),
    paddingBottom: px(12),
    paddingLeft: px(16),
    paddingRight: px(16),
  },
  activeUserItem: { borderColor: '#333333' },
  defaultUserItem: { borderColor: '#f7f7fb' },
  userItemText: {
    flex: 1,
    height: px(22),
    fontWeight: 'normal',
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  mb24: { marginBottom: px(12) },
  numPop: {
    width: '100%',
    height: px(54),
    padding: px(16),
    position: 'relative',
  },
  titleTextPop: {
    height: px(22),
    fontWeight: 'bold',
    fontSize: fontSize(16),
    color: '#333333',
    lineHeight: px(22),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  contentBox: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
    height: px(339),
    marginLeft: px(24),
    marginRight: px(24),
    marginTop: px(5),
    paddingTop: px(16),
    paddingBottom: px(16),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
  },
  pl48: { paddingLeft: px(24) },
  pr32: { paddingRight: px(16) },
  rowText1: {
    height: px(20),
    fontWeight: 'bold',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  tagBox: {
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    lineHeight: px(20),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  color1: { color: '#ff873d' },
  color2: { color: '#37c22a' },
  color10: { color: '#999999' },
  color20: { color: '#e5140d' },
  inviteCode: {
    height: px(50),
    fontWeight: 'bold',
    fontSize: fontSize(36),
    color: '#333333',
    lineHeight: px(50),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  popTime: {
    width: px(279),
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  timeBoxPop: {
    width: px(307),
    height: px(77),
    padding: px(14),
    borderRadius: px(12),
    borderWidth: px(0.5),
    borderStyle: 'solid',
    borderColor: '#ebebeb',
  },
  mr12: { marginRight: px(6) },
  mb8: { marginBottom: px(4) },
  dateTextPop: {
    height: px(20),
    fontWeight: 'normal',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  dateTime: {
    height: px(25),
    fontWeight: 'normal',
    fontSize: fontSize(18),
    color: '#333333',
    lineHeight: px(25),
    textAlign: 'left',
    fontStyle: 'normal',
    textTransform: 'none',
  },
  popupCode: {
    paddingLeft: px(24),
    paddingRight: px(24),
  },
  cancalBtnPop: {
    width: px(156),
    height: px(48),
    borderRadius: px(12),
    borderWidth: px(1),
    borderStyle: 'solid',
    borderColor: 'rgba(0, 0, 0, 0.1)',
    fontWeight: 'normal',
  },
  cancalBtnText: {
    fontSize: fontSize(16),
    lineHeight: px(44),
    color: '#999999',
    textAlign: 'center',
  },
  confirmBtnPop: {
    width: px(156),
    height: px(48),
    marginLeft: px(15),
    borderRadius: px(12),
  },
  confirmBtnTextPop: {
    fontWeight: '500',
    lineHeight: px(44),
    fontSize: fontSize(16),
    color: '#ffffff',
    textAlign: 'center',
  },
  shareBtn: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: px(20),
    paddingRight: px(20),
    margin: 0,
    color: '#ffffff',
  },
  messageBadge: {
    position: 'absolute',
    bottom: px(12),
    right: px(-8),
    height: px(18),
    paddingLeft: px(6),
    paddingRight: px(6),
    paddingTop: px(1),
    paddingBottom: px(1),
    backgroundColor: '#ff2b24',
    borderRadius: px(96),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  messageBadgeText: {
    height: px(17),
    fontSize: fontSize(12),
    color: '#ffffff',
    lineHeight: px(17),
    textAlign: 'center',
    fontStyle: 'normal',
    textTransform: 'none',
  },
});
