import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  content: {
    width: '100%',
    paddingHorizontal: 24,
  },
  footer: {
    width: '100%',
    paddingBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  btnPositionImageContent: {
    width: '100%',
    height: 184,
    borderRadius: 12,
    // iOS
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 16,
    // Android
    elevation: 8,
    shadowColor: '#000',
    marginTop: 114,
    overflow: 'hidden',
  },
  btnPositionImage: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    resizeMode: 'contain',
  },
  btnPositionImageText: {
    fontWeight: '500',
    fontSize: 18,
    color: '#333333',
    textAlign: 'center',
    lineHeight: 25,
    marginTop: 48,
  },
  deviceInfoSection: {
    width: '100%',
    marginTop: 30,
    padding: 16,
    backgroundColor: '#f7f7fb',
    borderRadius: 12,
  },
  deviceInfoItemLabel: {
    fontWeight: '400',
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
  },
  deviceInfoItemIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  deviceInfoItemIconText: {
    fontWeight: '400',
    fontSize: 14,
    color: '#FF873D',
    lineHeight: 20,
  },
  cancelBtn: {
    width: 94,
    height: 30,
    borderRadius: 12,
    backgroundColor: '#f7f7fb',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 34,
    marginTop: 16,
    display: 'flex',
    flexDirection: 'row',
    gap: 4,
  },
  cancelText: {
    fontSize: 14,
    color: '#333333',
    fontWeight: '400',
    lineHeight: 20,
  },
  btnText: {
    width: '100%',
    height: '100%',
  },
  btnTextInner: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
  },
  countdownContainer: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countdownText: {
    fontSize: 16,
    color: '#333333',
    fontWeight: '600',
  },
  countdownNumber: {
    marginLeft: 8,
    color: '#ff873d',
  },
  card: {
    width: '100%',
    marginTop: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#f7f7fb',
    borderRadius: 12,
  },
  rowMargin: {
    marginBottom: 12,
  },
  cardItem: {
    marginBottom: 12,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#333333',
    marginRight: 8,
  },
  cardItemText: {
    flex: 1,
    fontSize: 14,
    color: '#333333',
    fontWeight: '600',
    lineHeight: 20,
  },
  deviceName: {
    color: '#ff873d',
    fontWeight: '700',
  },
  iconWrapper: {
    marginTop: 24,
    marginBottom: 19,
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
  },
  titleWrapper: {
    marginBottom: 18,
    position: 'relative',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 8,
  },
  titleIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    position: 'absolute',
    right: 0,
    top: 5,
  },
  titleIconText: {
    fontSize: 14,
    color: '#333333',
    fontWeight: 'bold',
  },
  infoSection: {
    width: '100%',
    gap: 12,
    marginBottom: 24,
  },
  infoBox: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 15,
    color: '#6b7280',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 15,
    color: '#333333',
    fontWeight: 'bold',
  },
  pinValue: {
    fontSize: 20,
    color: '#333333',
    fontWeight: '700',
    letterSpacing: 4,
    margin: 0,
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  copyText: {
    marginLeft: 6,
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '600',
  },
  tips: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 25,
    marginTop: 10,
  },
  tipsText: {
    fontSize: 15,
    color: '#333333',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  footerWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
});

export default styles;
