import { px, fontSize } from '@/utils/ui';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  content: {
    width: '100%',
    paddingHorizontal: px(24),
  },
  footer: {
    width: '100%',
    paddingBottom: px(12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  iconWrapper2: {
    marginTop: px(32),
    marginBottom: px(28),
    width: px(64),
    height: px(64),
    borderRadius: px(32),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
  },
  tipsLabel: {
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(17),
    width: '100%',
    marginBottom: px(8),
  },
  btnPositionImageContent: {
    width: '100%',
    height: px(184),
    borderRadius: px(12),
    // iOS
    shadowOffset: { width: 0, height: px(8) },
    shadowOpacity: 1,
    shadowRadius: px(16),
    // Android
    elevation: px(8),
    shadowColor: '#000',
    marginBottom: px(24),
    overflow: 'hidden',
  },
  btnPositionImage: {
    width: '100%',
    height: '100%',
    borderRadius: px(12),
    resizeMode: 'contain',
  },
  btnPositionImageText: {
    fontWeight: '500',
    fontSize: fontSize(18),
    color: '#333333',
    textAlign: 'center',
    lineHeight: px(25),
    marginTop: px(48),
  },
  deviceInfoSection: {
    width: '100%',
    marginTop: px(30),
    padding: px(16),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
  },
  deviceInfoItemLabel: {
    fontWeight: '400',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
  },
  deviceInfoItemIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: px(2),
  },
  deviceInfoItemIconText: {
    fontWeight: '400',
    fontSize: fontSize(14),
    color: '#FF873D',
    lineHeight: px(20),
  },
  cancelBtn: {
    width: px(94),
    height: px(30),
    borderRadius: px(12),
    backgroundColor: '#f7f7fb',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: px(34),
    marginTop: px(16),
    display: 'flex',
    flexDirection: 'row',
    gap: px(4),
  },
  cancelText: {
    fontSize: fontSize(14),
    color: '#333333',
    fontWeight: '400',
    lineHeight: px(20),
  },
  btnText: {
    width: '100%',
    height: '100%',
  },
  btnTextInner: {
    color: '#ffffff',
    fontSize: fontSize(16),
    fontWeight: '500',
    lineHeight: px(22),
  },
  countdownContainer: {
    marginTop: px(12),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countdownText: {
    fontSize: fontSize(16),
    color: '#333333',
    fontWeight: '600',
  },
  countdownNumber: {
    marginLeft: px(8),
    color: '#ff873d',
  },
  card: {
    width: '100%',
    marginTop: px(16),
    paddingVertical: px(16),
    paddingHorizontal: px(16),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
  },
  rowMargin: {
    marginBottom: px(12),
  },
  cardItem: {
    marginBottom: px(12),
  },
  dot: {
    width: px(6),
    height: px(6),
    borderRadius: px(3),
    backgroundColor: '#333333',
    marginRight: px(8),
  },
  cardItemText: {
    flex: 1,
    fontSize: fontSize(14),
    color: '#333333',
    fontWeight: '600',
    lineHeight: px(20),
  },
  deviceName: {
    color: '#ff873d',
    fontWeight: '700',
  },
  iconWrapper: {
    marginTop: px(24),
    marginBottom: px(19),
    width: px(64),
    height: px(64),
    borderRadius: px(32),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f3f4f6',
  },
  titleWrapper: {
    marginBottom: px(18),
    position: 'relative',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: fontSize(20),
    fontWeight: '700',
    color: '#333333',
    marginBottom: px(8),
  },
  titleIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: px(2),
    position: 'absolute',
    right: px(0),
    top: px(5),
  },
  titleIconText: {
    fontSize: fontSize(14),
    color: '#333333',
    fontWeight: 'bold',
  },
  infoSection: {
    width: '100%',
    gap: px(12),
    marginBottom: px(24),
  },
  infoBox: {
    width: '100%',
    paddingVertical: px(12),
    paddingHorizontal: px(16),
    backgroundColor: '#f3f4f6',
    borderRadius: px(12),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: fontSize(15),
    color: '#6b7280',
    marginBottom: px(4),
  },
  infoValue: {
    fontSize: fontSize(15),
    color: '#333333',
    fontWeight: 'bold',
  },
  pinValue: {
    fontSize: fontSize(20),
    color: '#333333',
    fontWeight: '700',
    letterSpacing: px(4),
    margin: px(0),
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: px(8),
  },
  copyText: {
    marginLeft: px(6),
    fontSize: fontSize(12),
    color: '#6b7280',
    fontWeight: '600',
  },
  tips: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: px(25),
    marginTop: px(10),
  },
  tipsText: {
    fontSize: fontSize(15),
    color: '#333333',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  footerWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  footetText: {
    fontWeight: '500',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    marginBottom: px(24),
  },
});

export default styles;
