import { px, fontSize } from '@/utils/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    flexDirection: 'column',
    alignItems: 'center',
    paddingLeft: px(24),
    paddingRight: px(24),
  },
  navTitle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: px(8),
  },
  gatewayName: {
    paddingHorizontal: px(7),
    paddingVertical: px(4),
    backgroundColor: '#dcedff',
    borderRadius: px(6),
    alignItems: 'center',
    justifyContent: 'center',
  },
  gatewayNameText: {
    fontSize: fontSize(12),
    fontWeight: '400',
    color: '#1890ff',
    lineHeight: px(17),
  },
  navTitleText: {
    fontSize: fontSize(16),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: px(12),
  },
  label: {
    fontSize: fontSize(14),
    fontWeight: '700',
    color: '#333333',
    flexDirection: 'column',
    justifyContent: 'center',
    width: px(88),
  },
  input: {
    flex: 1,
    fontSize: fontSize(14),
    textAlign: 'right',
  },
  value: {
    fontSize: fontSize(14),
    fontWeight: '400',
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'right',
    flex: 1,
  },
  deviceSectionBox: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deviceSection: {
    fontWeight: '700',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    marginTop: px(16),
    marginBottom: px(12),
  },
  bindDeviceToast: {
    height: px(17),
    fontWeight: '400',
    fontSize: fontSize(12),
    color: '#ff873d',
    lineHeight: px(17),
    textAlign: 'left',
  },
  deviceContent: {
    width: '100%',
    flex: 1,
  },
  deviceItem: {
    width: '100%',
    height: px(60),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
    padding: px(12),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: px(12),
  },
  deviceImg: {
    width: px(36),
    height: px(36),
  },
  itemName: {
    fontWeight: '700',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    textAlign: 'left',
    flex: 1,
    paddingLeft: px(12),
  },
  radioImg: {
    width: px(20),
    height: px(20),
  },
  pageFooter: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: px(8),
  },
  createToast: {
    marginBottom: px(12),
    fontWeight: '400',
    fontSize: fontSize(14),
    color: '#999999',
    lineHeight: px(20),
    textAlign: 'center',
  },
  sureCreateBtn: {
    width: px(196),
    height: px(48),
    backgroundColor: '#333333',
    borderRadius: px(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  sureCreateBtnText: {
    color: '#ffffff',
    fontSize: fontSize(16),
    fontWeight: '500',
  },
  disabledBtn: {
    backgroundColor: '#999999',
  },
  emptyContainer: {
    flexGrow: 1,
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    marginTop: px(50),
  },
  emptyImage: {
    width: px(120),
    height: px(120),
  },
  emptyText: {
    fontSize: fontSize(14),
    color: '#666666',
    marginTop: px(16),
  },
  roundBg: {
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: px(10),
    paddingVertical: px(5),
    flexDirection: 'row',
  },
  labels: {
    fontSize: fontSize(14),
    fontWeight: '600',
    color: '#333333',
    lineHeight: px(20),
  },
  paddingH16: {
    paddingHorizontal: px(16),
  },
  popTitle: {
    fontSize: fontSize(16),
    fontWeight: '500',
    color: '#333333',
    lineHeight: px(22),
  },
  popSubTip: {
    paddingTop: px(16),
    paddingBottom: px(4),
    fontSize: fontSize(12),
    color: '#666',
    lineHeight: px(17),
    textAlign: 'center',
  },
  btnContainerWrapper: {
    paddingTop: px(16),
    paddingBottom: px(8),
  },

  btnContainer: {
    width: px(156),
    paddingVertical: px(13),
    borderRadius: px(12),
    display: 'flex',
    justifyContent: 'center',
    alignContent: 'center',
  },

  btnContainerClose: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },

  btnContainerCloseText: {
    color: '#999999',
    fontSize: fontSize(16),
    textAlign: 'center',
  },

  btnContainerConfirm: {
    marginLeft: px(15),
    fontSize: fontSize(16),
  },

  btnContainerConfirmText: {
    color: '#ffffff',
    fontSize: fontSize(16),
    fontWeight: 'bold',
    textAlign: 'center',
  },
  card: {
    marginHorizontal: px(12),
    marginTop: px(12),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
    padding: px(12),
  },
  username: {
    fontWeight: 'bold',
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
  },
});
