import { px, fontSize } from '@/utils/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    paddingHorizontal: px(24),
    paddingTop: px(16),
  },
  pairedBox: {
    width: '100%',
    alignItems: 'center',
    marginTop: px(40),
    paddingHorizontal: px(12),
  },
  gif: {
    width: px(360),
    height: px(180),
  },
  statusText: {
    marginTop: px(16),
    fontSize: fontSize(16),
    fontWeight: '700',
    color: '#333333',
    textAlign: 'center',
    lineHeight: px(22),
  },
  card: {
    width: '100%',
    paddingHorizontal: px(12),
    paddingVertical: px(16),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
  },
  connectedCard: {
    marginTop: px(24),
  },
  cardTitle: {
    fontSize: fontSize(14),
    fontWeight: '700',
    color: '#333333',
    marginBottom: px(8),
  },
  cardItemTexts: {
    fontSize: fontSize(14),
    fontWeight: '700',
    color: '#333333',
    lineHeight: px(20),
  },
  cardText: {
    fontSize: fontSize(14),
    color: '#333333',
    lineHeight: px(20),
    marginBottom: px(6),
  },
  toggleBtn: {
    marginTop: px(12),
    height: px(44),
    borderRadius: px(12),
    backgroundColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnText: {
    color: '#ffffff',
    fontSize: fontSize(14),
    fontWeight: '700',
  },
  unpairedBox: {
    width: '100%',
    paddingTop: px(40),
    alignItems: 'center',
  },
  unpairedTitle: {
    fontSize: fontSize(18),
    fontWeight: '700',
    color: '#333333',
    marginBottom: px(8),
  },
  unpairedDesc: {
    fontSize: fontSize(14),
    color: '#666666',
    textAlign: 'center',
    marginBottom: px(20),
  },
  actions: {
    width: '100%',
    alignItems: 'center',
  },
  btnText: {
    color: '#ffffff',
    fontSize: fontSize(16),
    fontWeight: 'bold',
    lineHeight: px(22),
  },
  footer: {
    paddingVertical: px(12),
    paddingHorizontal: px(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerLabel: {
    fontSize: fontSize(14),
    color: '#333333',
    fontWeight: '600',
  },
  footerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  footerValue: {
    fontSize: fontSize(14),
    color: '#333333',
    fontWeight: '700',
    marginRight: px(6),
  },
  footerArrow: {
    fontSize: fontSize(18),
    color: '#999999',
    marginTop: px(-1),
  },
  rowMargin32: {
    marginBottom: px(16),
  },
  cardItemText: {
    flex: 1,
    fontSize: fontSize(14),
    color: '#333333',
    fontWeight: 'bold',
    lineHeight: px(20),
  },
  rowMargin: {
    marginBottom: px(8),
  },
  dotWrapper: {
    width: px(20),
    height: px(20),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dot: {
    width: px(6),
    height: px(6),
    borderRadius: px(3),
    backgroundColor: '#999999',
    marginRight: px(8),
  },
  buttonTipsText: {
    fontSize: fontSize(14),
    color: '#999999',
    lineHeight: px(20),
    marginBottom: px(8),
  },
  btn: {
    height: px(48),
    borderRadius: px(16),
    marginTop: px(8),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerContainer: {
    paddingHorizontal: px(24),
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: px(37),
  },
  footerTextWrapper: {
    width: '100%',
    height: px(48),
    backgroundColor: '#f7f7fb',
    borderRadius: px(12),
    paddingHorizontal: px(12),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: fontSize(14),
    color: '#ff873d',
    fontWeight: '700',
    lineHeight: px(20),
  },
  footerRightContent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: px(4),
  },
});
